/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - Go 开发框架 (BlueKing - Go Framework) available.
 * Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *	https://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

package envx_test

import (
	"fmt"
	"os"
	"os/exec"
	"testing"

	"github.com/stretchr/testify/assert"

	"github.com/TencentBlueKing/blueapps-go/pkg/utils/envx"
)

// 不存在的环境变量
func TestGetNotExists(t *testing.T) {
	ret := envx.Get("NOT_EXISTS_ENV_KEY", "ENV_VAL")
	assert.Equal(t, "ENV_VAL", ret)
}

// 已存在的环境变量
func TestGetExists(t *testing.T) {
	ret := envx.Get("PATH", "")
	assert.NotEqual(t, "", ret)
}

// 不存在的环境变量
func TestMustGetNotExists(t *testing.T) {
	defer func() {
		assert.Equal(t, "required environment variable NOT_EXISTS_ENV_KEY unset", recover())
	}()

	_ = envx.MustGet("NOT_EXISTS_ENV_KEY")
}

// 已存在的环境变量
func TestMustGetExists(t *testing.T) {
	ret := envx.MustGet("PATH")
	assert.NotEqual(t, "", ret)
}

// 测试 GetBool 函数（True 场景）
func TestGetBoolTrueCase(t *testing.T) {
	tests := []struct {
		key   string
		value string
	}{
		{"TRUE_1", "1"},
		{"TRUE_2", "t"},
		{"TRUE_3", "T"},
		{"TRUE_4", "true"},
		{"TRUE_5", "TRUE"},
		{"TRUE_6", "True"},
	}
	for _, tt := range tests {
		_ = os.Setenv(tt.key, tt.value)
		ret := envx.GetBool(tt.key)
		assert.True(t, ret)
	}
}

// 测试 GetBool 函数（False 场景）
func TestGetBoolFalseCase(t *testing.T) {
	tests := []struct {
		key   string
		value string
	}{
		{"FALSE_0", ""},
		{"FALSE_1", "0"},
		{"FALSE_2", "f"},
		{"FALSE_3", "F"},
		{"FALSE_4", "false"},
		{"FALSE_5", "FALSE"},
		{"FALSE_6", "False"},
	}
	for _, tt := range tests {
		_ = os.Setenv(tt.key, tt.value)
		ret := envx.GetBool(tt.key)
		assert.False(t, ret)
	}
}

// 测试 GetBool 函数（不存在的环境变量 -> false）
func TestGetBoolNotExistKey(t *testing.T) {
	ret := envx.GetBool("NOT_EXISTS_KEY")
	assert.False(t, ret)
}

// 测试用数据，测试 Fernet 算法的加解密是否正常
func TestDecryptEncryptedEnvironment(t *testing.T) {
	const (
		secretKey  = "PIMCuSRiVqBg5eSzQqZZrOhGFSUtrlS-8_JlIpjHt0A="
		ciphertext = "bkpaas_enc$bkcrypt$gAAAAAAAAAAAKImpy2TXu79Ak3Ed8cd2Yy-muwedawnnxV8BMoZFoBF840wpyznXJaBfbXwgEa7KH7SnRJR7EvGeJieimCK8zA=="
	)

	t.Setenv("BKPAAS_ENCRYPT_SECRET_KEY", secretKey)
	t.Setenv("BKPAAS_ENCRYPTED_ENV_KEYS", " ENCRYPTED, NOT_ENCRYPTED, MISSING, ")
	t.Setenv("ENCRYPTED", ciphertext)
	t.Setenv("NOT_ENCRYPTED", "plaintext")

	err := envx.DecryptEncryptedEnvironment()
	assert.NoError(t, err)
	assert.Equal(t, "platform secret", os.Getenv("ENCRYPTED"))
	assert.Equal(t, "plaintext", os.Getenv("NOT_ENCRYPTED"))
}

// 测试 os.Setenv 是否会在当前进程中生效，并能被后续启动的子进程继承。
func TestSetenvScope(t *testing.T) {
	const (
		key       = "TEST_ENV_KEY"
		helperKey = "TEST_SETENV_SCOPE_HELPER"
	)

	if os.Getenv(helperKey) == "1" {
		_, _ = fmt.Fprint(os.Stdout, os.Getenv(key))
		os.Exit(0)
	}

	original, existed := os.LookupEnv(key)

	// DecryptEncryptedEnvironment 使用 os.Setenv 将解密值写回当前进程。
	err := os.Setenv(key, "decrypted")
	assert.NoError(t, err)
	t.Cleanup(func() {
		if existed {
			_ = os.Setenv(key, original)
			return
		}
		_ = os.Unsetenv(key)
	})

	// 当前进程后续通过标准库或 envx 封装读取时，都能获取写回后的值。
	assert.Equal(t, "decrypted", os.Getenv(key))
	assert.Equal(t, "decrypted", envx.Get(key, "fallback"))

	// os.Setenv 修改后的环境会被后续启动的真实子进程继承。
	cmd := exec.Command(os.Args[0], "-test.run=^TestSetenvScope$")
	cmd.Env = append(os.Environ(), helperKey+"=1")
	output, err := cmd.Output()
	assert.NoError(t, err)
	assert.Equal(t, "decrypted", string(output))
}

func TestDecryptEncryptedEnvironmentSM4CTR(t *testing.T) {
	// Generated by the BlueKing Python SDK's SM4CTR EncryptHandler with the
	// matching 32-character platform key.
	t.Setenv("BKPAAS_ENCRYPT_SECRET_KEY", "0123456789abcdef0123456789abcdef")
	t.Setenv("BKPAAS_ENCRYPTED_ENV_KEYS", "ENCRYPTED")
	t.Setenv("ENCRYPTED", "bkpaas_enc$sm4ctr$39vVxx0KqMvSPqL9K2nmQYamp+cGOQjy0dyB7ThK")

	err := envx.DecryptEncryptedEnvironment()
	assert.NoError(t, err)
	assert.Equal(t, "shangmi secret", os.Getenv("ENCRYPTED"))
}

func TestDecryptEncryptedEnvironmentSkipsWhenPlatformSettingsMissing(t *testing.T) {
	t.Setenv("BKPAAS_ENCRYPT_SECRET_KEY", "")
	t.Setenv("BKPAAS_ENCRYPTED_ENV_KEYS", "ENCRYPTED")
	t.Setenv("ENCRYPTED", "bkpaas_enc$bkcrypt$not-a-token")

	err := envx.DecryptEncryptedEnvironment()
	assert.NoError(t, err)
	assert.Equal(t, "bkpaas_enc$bkcrypt$not-a-token", os.Getenv("ENCRYPTED"))
}

func TestDecryptEncryptedEnvironmentPreservesUnheadedPayload(t *testing.T) {
	t.Setenv("BKPAAS_ENCRYPT_SECRET_KEY", "unused")
	t.Setenv("BKPAAS_ENCRYPTED_ENV_KEYS", "ENCRYPTED")
	t.Setenv("ENCRYPTED", "bkpaas_enc$legacy-payload")

	err := envx.DecryptEncryptedEnvironment()
	assert.NoError(t, err)
	assert.Equal(t, "legacy-payload", os.Getenv("ENCRYPTED"))
}

func TestDecryptEncryptedEnvironmentRejectsInvalidCiphertext(t *testing.T) {
	t.Setenv("BKPAAS_ENCRYPT_SECRET_KEY", "PIMCuSRiVqBg5eSzQqZZrOhGFSUtrlS-8_JlIpjHt0A=")
	t.Setenv("BKPAAS_ENCRYPTED_ENV_KEYS", "ENCRYPTED")
	t.Setenv("ENCRYPTED", "bkpaas_enc$bkcrypt$not-a-token")

	err := envx.DecryptEncryptedEnvironment()
	assert.ErrorContains(t, err, "decrypt environment variable ENCRYPTED")
}
